"""baseline sqlite

Revision ID: 6197a5fddbe0
Revises: 
Create Date: 2025-09-08 16:39:41.641242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '6197a5fddbe0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('youtube', 'tiktok', 'instagram', 'x', 'facebook', 'twitch', name='platform_name_enum', native_enum=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('platform_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_account_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_account_platform_id'), ['platform_id'], unique=False)

    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('platform_account_id', sa.Integer(), nullable=True),
    sa.Column('external_channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sa.CHAR(length=2), nullable=True),
    sa.Column('language', sa.CHAR(length=2), nullable=True),
    sa.Column('custom_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('banner_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_monetized', sa.Boolean(), nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.create_index('ix_channel_account', ['platform_account_id'], unique=False)

    op.create_table('oauth_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_account_id', sa.Integer(), nullable=False),
    sa.Column('access_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scopes', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_credential_platform_account_id'), ['platform_account_id'], unique=False)

    op.create_table('channel_daily_metrics',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subscribers_total', sa.BigInteger(), nullable=True),
    sa.Column('subscribers_gained', sa.BigInteger(), nullable=True),
    sa.Column('subscribers_lost', sa.BigInteger(), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('watch_time_minutes', sa.BigInteger(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('click_through_rate', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('estimated_revenue', sa.NUMERIC(precision=12, scale=4), nullable=True),
    sa.Column('revenue_currency', sa.CHAR(length=3), nullable=True),
    sa.CheckConstraint('click_through_rate >= 0 AND click_through_rate <= 100', name='ck_cdm_ctr_pct'),
    sa.CheckConstraint('estimated_revenue >= 0', name='ck_cdm_rev_nonneg'),
    sa.CheckConstraint('impressions >= 0', name='ck_cdm_impr_nonneg'),
    sa.CheckConstraint('subscribers_gained >= 0', name='ck_cdm_subs_gained_nonneg'),
    sa.CheckConstraint('subscribers_lost >= 0', name='ck_cdm_subs_lost_nonneg'),
    sa.CheckConstraint('subscribers_total >= 0', name='ck_cdm_subs_total_nonneg'),
    sa.CheckConstraint('views >= 0', name='ck_cdm_views_nonneg'),
    sa.CheckConstraint('watch_time_minutes >= 0', name='ck_cdm_wtm_nonneg'),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'date')
    )
    op.create_table('channel_hourly_metrics',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('hour_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('watch_time_minutes', sa.BigInteger(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.Column('subscribers_gained', sa.BigInteger(), nullable=True),
    sa.Column('estimated_revenue', sa.NUMERIC(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'hour_start')
    )
    with op.batch_alter_table('channel_hourly_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_chm_channel_hour', ['channel_id', 'hour_start'], unique=False)

    op.create_table('user_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='channel_role_enum', native_enum=False), server_default='viewer', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_user_channel_pair')
    )
    with op.batch_alter_table('user_channel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_channel_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_channel_user_id'), ['user_id'], unique=False)

    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('external_video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('privacy_status', sa.Enum('public', 'unlisted', 'private', name='privacy_enum', native_enum=False), nullable=True),
    sa.Column('content_type', sa.Enum('video', 'short', 'reel', 'live', 'post', name='content_type_enum', native_enum=False), nullable=True),
    sa.Column('duration_seconds', sa.BigInteger(), nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_index('ix_video_channel_published', ['channel_id', 'published_at'], unique=False)

    op.create_table('video_daily_metrics',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('watch_time_minutes', sa.BigInteger(), nullable=True),
    sa.Column('avg_view_duration_seconds', sa.BigInteger(), nullable=True),
    sa.Column('avg_percent_viewed', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('click_through_rate', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('subs_gained_from_video', sa.BigInteger(), nullable=True),
    sa.Column('estimated_revenue', sa.NUMERIC(precision=12, scale=4), nullable=True),
    sa.Column('revenue_currency', sa.CHAR(length=3), nullable=True),
    sa.CheckConstraint('avg_percent_viewed >= 0 AND avg_percent_viewed <= 100', name='ck_vdm_apv_pct'),
    sa.CheckConstraint('avg_view_duration_seconds >= 0', name='ck_vdm_avd_nonneg'),
    sa.CheckConstraint('click_through_rate >= 0 AND click_through_rate <= 100', name='ck_vdm_ctr_pct'),
    sa.CheckConstraint('comments >= 0', name='ck_vdm_comments_nonneg'),
    sa.CheckConstraint('estimated_revenue >= 0', name='ck_vdm_rev_nonneg'),
    sa.CheckConstraint('impressions >= 0', name='ck_vdm_impr_nonneg'),
    sa.CheckConstraint('likes >= 0', name='ck_vdm_likes_nonneg'),
    sa.CheckConstraint('shares >= 0', name='ck_vdm_shares_nonneg'),
    sa.CheckConstraint('subs_gained_from_video >= 0', name='ck_vdm_subs_nonneg'),
    sa.CheckConstraint('views >= 0', name='ck_vdm_views_nonneg'),
    sa.CheckConstraint('watch_time_minutes >= 0', name='ck_vdm_wtm_nonneg'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'date')
    )
    op.create_table('video_hourly_metrics',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('hour_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('watch_time_minutes', sa.BigInteger(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.Column('subs_gained_from_video', sa.BigInteger(), nullable=True),
    sa.Column('estimated_revenue', sa.NUMERIC(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'hour_start')
    )
    with op.batch_alter_table('video_hourly_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_vhm_video_hour', ['video_id', 'hour_start'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_hourly_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_vhm_video_hour')

    op.drop_table('video_hourly_metrics')
    op.drop_table('video_daily_metrics')
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_index('ix_video_channel_published')

    op.drop_table('video')
    with op.batch_alter_table('user_channel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_channel_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_channel_channel_id'))

    op.drop_table('user_channel')
    with op.batch_alter_table('channel_hourly_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_chm_channel_hour')

    op.drop_table('channel_hourly_metrics')
    op.drop_table('channel_daily_metrics')
    with op.batch_alter_table('oauth_credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_credential_platform_account_id'))

    op.drop_table('oauth_credential')
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_index('ix_channel_account')

    op.drop_table('channel')
    with op.batch_alter_table('platform_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_account_platform_id'))
        batch_op.drop_index(batch_op.f('ix_platform_account_owner_user_id'))

    op.drop_table('platform_account')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('platform')
    # ### end Alembic commands ###
