"""init tables

Revision ID: 736ac77fac67
Revises: 
Create Date: 2025-08-26 14:56:26.820458

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736ac77fac67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('googleaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scopes_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_googleaccount_user_id'), 'googleaccount', ['user_id'], unique=False)
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_account_id', sa.Integer(), nullable=False),
    sa.Column('yt_channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['google_account_id'], ['googleaccount.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_google_account_id'), 'channel', ['google_account_id'], unique=False)
    op.create_index(op.f('ix_channel_user_id'), 'channel', ['user_id'], unique=False)
    op.create_index(op.f('ix_channel_yt_channel_id'), 'channel', ['yt_channel_id'], unique=False)
    op.create_table('metricdaily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('watch_time_min', sa.Integer(), nullable=False),
    sa.Column('avg_view_duration_sec', sa.Integer(), nullable=True),
    sa.Column('avg_pct_viewed', sa.Float(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('impressions_ctr_pct', sa.Float(), nullable=True),
    sa.Column('subs_gained', sa.Integer(), nullable=True),
    sa.Column('subs_lost', sa.Integer(), nullable=True),
    sa.Column('est_revenue_minor', sa.Integer(), nullable=True),
    sa.Column('rpm_minor', sa.Integer(), nullable=True),
    sa.Column('playback_cpm_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricdaily_channel_id'), 'metricdaily', ['channel_id'], unique=False)
    op.create_index(op.f('ix_metricdaily_date'), 'metricdaily', ['date'], unique=False)
    op.create_index(op.f('ix_metricdaily_video_id'), 'metricdaily', ['video_id'], unique=False)
    op.create_table('videomap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('yt_video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videomap_channel_id'), 'videomap', ['channel_id'], unique=False)
    op.create_index(op.f('ix_videomap_yt_video_id'), 'videomap', ['yt_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videomap_yt_video_id'), table_name='videomap')
    op.drop_index(op.f('ix_videomap_channel_id'), table_name='videomap')
    op.drop_table('videomap')
    op.drop_index(op.f('ix_metricdaily_video_id'), table_name='metricdaily')
    op.drop_index(op.f('ix_metricdaily_date'), table_name='metricdaily')
    op.drop_index(op.f('ix_metricdaily_channel_id'), table_name='metricdaily')
    op.drop_table('metricdaily')
    op.drop_index(op.f('ix_channel_yt_channel_id'), table_name='channel')
    op.drop_index(op.f('ix_channel_user_id'), table_name='channel')
    op.drop_index(op.f('ix_channel_google_account_id'), table_name='channel')
    op.drop_table('channel')
    op.drop_index(op.f('ix_googleaccount_user_id'), table_name='googleaccount')
    op.drop_table('googleaccount')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
